### ISSUE TITLE
Is there any forum-like capabilities?

### ISSUE THREAD

**Issue by ivan006** [pH-7/pH4Social#2]
Is there any forum-like capabilities?

**Comment by pH-7** [comment]
Hi there @ivan006, beside the in-built instant messenger, it doesn't offer any kind of forums (discussions board), but it does have a live chat.

If you are looking to a similar social networking CMS with a forum, I would suggest you to check out https://github.com/pH7Software/pH7-Social-Dating-CMS which is also 100% open source and free. v17.1.2 was released yesterday 🎉


Hope it helps! 😄
